### ISSUE TITLE
Other Engines

### ISSUE THREAD

**Issue by zauberparacelsus** [NewDavidg0/Smooth-Infinite-Voxel-Terrain#2]
Would it be possible to extend this so that it'll support other game engines, such as Godot Engine?

**Comment by AnkingLin** [comment]
It's a hard job.We need rewrite all script code to change the game engines,because game engines have different architectures.It's not like supporting OpenGL and DX9.
But if you have time to extend this game,you could contact with author.

**Comment by DXGatech** [comment]
Thanks @Cawell-Anki for the explanation!
Yes, it's possible, but it'll be hard and time consuming, as this project is created for unreal only. We'll have to replace unreal's c++ API and blueprint logics if we want to migrate it. Sorry that adding supports for other engines is not considered for now.
